services:
  app:
    build:
      context: ./mediaclub_laravel
    container_name: laravel_app
    restart: unless-stopped
    volumes:
      - /home/allison/env/.env:/var/www/.env:ro
    working_dir: /var/www
    networks:
      - web
    depends_on:
      - db

  webserver:
    image: nginx:alpine
    container_name: laravel_webserver
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./mediaclub_laravel:/var/www
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - web
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: always
    env_file:
      - /home/allison/env/prod.env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - web

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
    env_file:
      - /home/allison/env/prod.env
    networks:
      - web

volumes:
  db_data:

networks:
  web:
    driver: bridge

