http:
  routers:
    react:
      rule: "Host(`frontend.localhost`)"
      service: react-service
      entryPoints:
        - web

    laravel:
      rule: "Host(`backend.localhost`)"
      service: laravel-service
      entryPoints:
        - web

  services:
    react-service:
      loadBalancer:
        servers:
          - url: "http://frontend:3000"

    laravel-service:
      loadBalancer:
        servers:
          - url: "http://backend:9000"
